baseURL = 'https://nerdkunst.be/'
languageCode = 'nl-be'
title = 'NerdKunst'
theme = 'ananke'


DefaultContentLanguage = "nl"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.nl]
    title = "Nerdkunst"
    weight = 1
    contentDir = "content/nl"
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Nick"
  body_classes = "bodoni bg-light-gray"
  post_content_classes = "bodoni"
  favicon = "favicon.ico"
  site_logo = "images/nerdkunst-logo.png"
  description = "Omdat wetenschap en technologie ook gewoon mooi kunnen zijn."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
